title: D.LIU Blog
description: > # this means to ignore newlines until "baseurl:"
  D.LIU Personal Blog
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Dong Liu # add your name
author-img: d_liu.jpg
about-author: Welcome to my personal site # add description



social-email: guimet@foxmail.com 
social-github: liudoong # add your Github handle
social-instagram: don_dong_
social-linkedin: dong-liu # add your Linkedin handle



# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

mathjax: true #allow math equations globally

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 100
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
