title: D.LIU Blog
description: > # this means to ignore newlines until "baseurl:"
  D.LIU Personal Blog
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Dong Liu # add your name
author-img: 1557543914968.GPEG
about-author: I am an Economist # add description

social-github: liudoong # add your Github handle
social-linkedin: dong-liu # add your Linkedin handle
social-email: guimet@foxmail.com 

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
